### ISSUE TITLE
Invalid signature in request credentials.

### ISSUE THREAD

**Issue by mdumouchel** [duosecurity/duo_api_nodejs#2]
Hello,
I'm having issues sending any request with data to the Auth API using this module.  If I have a request without data such as enroll this module works fine and creates the user.  If I include data object to the request I get invalid signature in request.

```
var duo_api = require('duo_api');
var ikey = "xxxx";
var skey = "xxxx";
var host = "xxxx";
var client = new duo_api.Client(ikey, skey, host);
//This passes
client.jsonApiCall(
    'POST', '/auth/v2/enroll', {},
    function(res) {
      if (res.stat !== 'OK') {
        console.error('API call returned error: ' + res.message);
        process.exit(1);
     }

    res = res.response;
    console.log(res);
});
//This fails.
var user = {'username': 'mattD'};
client.jsonApiCall(
    'POST', '/auth/v2/enroll', user,
    function(res) {
      if (res.stat !== 'OK') {
        console.error('API call returned error: ' + res.message);
        process.exit(1);
     }

    res = res.response;
    console.log(res);
});
```

**Comment by chrisjgreen9** [comment]
I have been having the same issue with the same REST endpoint (enroll) using Java.  I see this was addressed almost 3 years ago...but eerily the same.

**Comment by ben-duo** [comment]
Hi, Chris.

I noticed one of your colleagues is in contact with Duo Support regarding the Java source code that resulted in this error. In addition to support's suggestions, one thing I've noticed specific to duo_client_java is that calling the signRequest method before addParam means the parameters in the signature don't match those received by the server.

If none of these ideas fix the issue then by all means take support up on their offer to debug the relevant source code. If it turns out there's a bug in our Java SDK similar to this Node issue then we'll update https://github.com/duosecurity/duo_client_java ASAP!

**Comment by chrisjgreen9** [comment]
Ben - Your hint reminded me that the parameters needed to be part of the both the body AND the signature, therefore I was able to get it to work now.  As an FYI, our Java implementation was developed without using your client code, therefore no issue with your client API.

**Comment by pflammertsma** [comment]
How have you come to the conclusion that `sig_version` should be included in the HMAC signing?

[According to the documentation](https://duo.com/docs/adminapi#authentication), the signature should only be generated over `date`, `method`, `host`, `path`, `params`, in that order.

It appears that signing fails in this implementation for three reasons:
- The order of the parameters for signing is incorrect.
- `sig_version` is incorrectly included into the signing string.
- If `sig_version != 4`, HMAC incorrectly uses `sha512` instead of `sha1`.

I get the impression something might have changed in Duo's v2 API since this repo was created, but I thought I'd point this out in case others are surprised to find it doesn't work.
